### ISSUE TITLE
SBB boilerplate code does not get populated correctly

### ISSUE THREAD

**Issue by tdevinda** [RestComm/jain-slee.eclipslee#2]
When the SLEE project is created and then an SBB is created, the class is not properly created.

Steps to recreate:
download the restcomm 2.8.0 package and install the eclipslee plugin to eclipsedir/plugins
open eclipse
create a new JAIN SLEE project
create new SBB under sbb/src/main/java
Press Finish (at any stage)

Result:
Code appears as below;

package lk.tdevinda.kelani;

import javax.slee.*;
**IMPORT_MOBICENTS_EXTENSIONS**
public abstract class ProxyOperationSbb implements Sbb, ProxyOperation {

```
public void onServiceStartedEvent(javax.slee.serviceactivity.ServiceStartedEvent event, ActivityContextInterface aci/*, EventContext eventContext*/) {
}
```

Expected outcome:
class without any markup

System details;
Toshiba Laptop running Windows 10 1511 (build 10586.164)
Eclipse:
Version: Mars.1 Release (4.5.1)
Build id: 20150924-1200
java:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by SergeyLee** [comment]
Hi @tdevinda!
I found this bug a two weeks ago and fixed it: https://github.com/RestComm/jain-slee.eclipslee/commit/06e79abb5fb6976d213a9aaf01e2f48194c72f56
Did you build EclipSLEE from github or download Restcomm JSLEE Release before 11 March?

**Comment by tdevinda** [comment]
I actually downloaded and copied the jar from the Restcomm zip file from [here ](https://github.com/RestComm/jain-slee/releases/tag/2.8.0.FINAL) on 25th. (may be the zip package was built earlier)
Tried to build the plugin from github but was not successful I will try again.

**Comment by SergeyLee** [comment]
You can download last build from https://mobicents.ci.cloudbees.com/view/JSLEE/job/Restcomm-JAIN-SLEE-Release/lastSuccessfulBuild/artifact/release/
Or EclipSLEE Plugin only (org.mobicents.eclipslee.servicecreation-2.0.0-SNAPSHOT.jar) from https://mobicents.ci.cloudbees.com/view/JSLEE/job/Restcomm-EclipSLEE-release/lastSuccessfulBuild/artifact/tools/eclipslee/plugin/plugins/org.mobicents.eclipslee.servicecreation/target/

**Comment by SergeyLee** [comment]
There were many problems with building EclipSLEE for correctly work and now it does not finish.
In near future I will add some issues for fixing these problems.

**Comment by tdevinda** [comment]
Yes. build does not finish. But the plugin works from the location you specified. I think the original bug I reported is actually fixed. 
Your call to close this or not :+1: 

Thanks for the prompt response.

**Comment by SergeyLee** [comment]
You are welcome! :)
I have some problems with using it too. If you find new bugs please add issues :+1:
